// REACT/src/pages/TicketManager.jsx
import React, { useState, useEffect } from 'react';
import { db } from '../firebase';
import { useAuth } from '../context/AuthContext';
import { 
    collection, 
    getDocs, 
    addDoc, 
    updateDoc, 
    deleteDoc, 
    doc 
} from 'firebase/firestore';

const TicketManager = () => {
    
    const [tickets, setTickets] = useState([]);
  
    const [newTicketTitle, setNewTicketTitle] = useState('');
    const [newTicketDesc, setNewTicketDesc] = useState('');
    const ticketsCollectionRef = collection(db, "tickets");

let { loading } = useAuth();

useEffect(() => {
        const getTickets = async () => {
            try {
               
                const data = await getDocs(ticketsCollectionRef);
                let fetchedTickets = data.docs.map((document) => ({ 
                    ...document.data(), 
                    id: document.id 
                }));
                setTickets(fetchedTickets);

            } catch (error) {
                console.error("Couldn't Fetch tickers:", error);
            }
        };

        getTickets();
    }, []);


    const createTicket = async () => {
        if (!newTicketTitle || !newTicketDesc) return;
        
        const newTicketData = { 
            title: newTicketTitle, 
            description: newTicketDesc,
            status: "Open",
            createdAt: new Date()
        };

        try {
        
            const docRef = await addDoc(ticketsCollectionRef, newTicketData);
            
           
            setTickets([
                ...tickets, 
                { ...newTicketData, id: docRef.id }
            ]);
            
            
            setNewTicketTitle('');
            setNewTicketDesc('');
            
        } catch (error) {
            console.error("Couldn't create ticket:", error);
        }
    };

    const deleteTicket = async (id) => {
        try {
          
            const ticketDoc = doc(db, "tickets", id); 
   
            await deleteDoc(ticketDoc);

            setTickets(tickets.filter(ticket => ticket.id !== id));
            
        } catch (error) {
            console.error("Couldn't delete the ticket:", error);
        }
    };

    
    
   // src/pages/TicketManager.jsx (Inside TicketManager component)

// Define the order of the status flow
const STATUS_SEQUENCE = ["Open", "InProgress", "Closed"];

const getNextStatus = (currentStatus) => {
    switch (currentStatus) {
        case "Open":
            return "InProgress";
        case "InProgress":
            return "Closed";
        case "Closed":
            return "Open"; 
        default:
            return "Open";
    }
};

const toggleStatus = async (id, currentStatus) => {

    const newStatus = getNextStatus(currentStatus);
    
    try {
        const ticketDoc = doc(db, "tickets", id);
       
        await updateDoc(ticketDoc, { status: newStatus });

        setTickets(tickets.map(ticket => 
            ticket.id === id ? { ...ticket, status: newStatus } : ticket
        ));
        
    } catch (error) {
        console.error("Couldn't update ticket status:", error);
    }
};
  
    return (
        <div className="container mx-auto p-4 max-w-4xl bg-gray-800 ">
            <h1 className="text-4xl font-bold text-blue-500 mb-6">Ticket Dashboard</h1>

            {/* Form for Adding New Tickets */}
            <div className="mb-8 p-6 bg-gray-800 rounded-lg shadow-lg">
                <h2 className="text-2xl font-semibold mb-4 text-white">Add New Ticket</h2>
                <div className="space-y-4">
                    <input 
                        type="text" 
                        placeholder="Ticket Title"
                        value={newTicketTitle}
                        onChange={(e) => setNewTicketTitle(e.target.value)}
                        className="w-full p-3 rounded bg-gray-700 text-white border-gray-600"
                    />
                    <textarea 
                        placeholder="Description"
                        value={newTicketDesc}
                        onChange={(e) => setNewTicketDesc(e.target.value)}
                        className="w-full p-3 rounded bg-gray-700 text-white border-gray-600"
                        rows="3"
                    ></textarea>
                    <button 
                        onClick={createTicket} 
                        className="w-full py-3 bg-green-600 hover:bg-green-700 rounded-lg font-bold text-white transition duration-300"
                    >
                        Create Ticket
                    </button>
                </div>
            </div>

            {/* List of Tickets */}
            <h2 className="text-3xl font-semibold mb-4 text-white">Current Tickets ({tickets.length})</h2>
            <div className="space-y-4">
                {tickets.map((ticket) => (
                    <div key={ticket.id} className="p-4 bg-gray-700 rounded-lg shadow flex justify-between items-center">
                        <div>
                            <h3 className="text-xl font-bold text-yellow-400">{ticket.title}</h3>
                            <p className="text-gray-300">{ticket.description}</p>
                            <p className={`font-semibold text-sm mt-1 ${ticket.status === 'Open' ? 'text-red-400' : 'text-green-400'}`}>
                                Status: {ticket.status}
                            </p>
                        </div>
                        <div className="space-x-2 flex items-center">
                            {/* Toggle Status Button */}
                            <button 
                            onClick={() => toggleStatus(ticket.id, ticket.status)}
            className={`px-3 py-1 rounded text-sm font-semibold text-white transition duration-200 
                        ${ticket.status === 'Open' ? 'bg-indigo-500 hover:bg-indigo-600' : 
                          ticket.status === 'InProgress' ? 'bg-yellow-500 hover:bg-yellow-600' : 
                          'bg-green-600 hover:bg-green-700'}`}
                            >
                                {ticket.status === 'Open' && 'Start Work'}
            {ticket.status === 'InProgress' && 'Complete'}
            {ticket.status === 'Closed' && 'Re-open'}
                            </button>
                            
                            {/* Delete Button */}


                            <button 
                                onClick={() => deleteTicket(ticket.id)}
                                className="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded text-sm font-semibold transition duration-200"
                            >
                                Delete
                            </button>
                        </div>
                    </div>
                ))}
            </div>
    {tickets.length === 0 && !loading && <p className="text-gray-400 text-center mt-8">No tickets found. Add one above!</p>}
        </div>
);};

export default TicketManager;

// Vue/src/Views/TicketManager.vue
<script setup>
import { ref, computed } from 'vue';

const generateId = () => Date.now() + Math.floor(Math.random() * 1000);

const mockTickets = [
    { id: generateId(), title: 'Fix broken contact form', description: 'The submission button throws a 500 error on production.', status: 'Open', createdAt: new Date() },
    { id: generateId(), title: 'Implement dark mode toggle', description: 'Add a user-friendly button to switch between themes.', status: 'InProgress', createdAt: new Date() },
];

const tickets = ref(mockTickets);
const newTicketTitle = ref('');
const newTicketDesc = ref('');

const sortedTickets = computed(() => {
    return tickets.value.slice().sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
});

const getNextStatus = (currentStatus) => {
    switch (currentStatus) {
        case "Open": return "InProgress";
        case "InProgress": return "Closed";
        case "Closed": return "Open"; 
        default: return "Open";
    }
};

const createTicket = () => {
    if (!newTicketTitle.value || !newTicketDesc.value) return;

    const newTicketData = {
        id: generateId(),
        title: newTicketTitle.value,
        description: newTicketDesc.value,
        status: "Open",
        createdAt: new Date(),
    };

    tickets.value.push(newTicketData);
    
    newTicketTitle.value = '';
    newTicketDesc.value = '';
};

const deleteTicket = (id) => {
    tickets.value = tickets.value.filter(ticket => ticket.id !== id);
};

const toggleStatus = (id, currentStatus) => {
    const newStatus = getNextStatus(currentStatus);
    
    tickets.value = tickets.value.map(ticket => {
        if (ticket.id === id) {
            return { ...ticket, status: newStatus };
        }
        return ticket;
    });
};

const getStatusClass = (status) => {
    if (status === 'Open') return 'status-open';
    if (status === 'InProgress') return 'status-in-progress';
    if (status === 'Closed') return 'status-closed';
    return 'status-default';
};
</script>

<template>
    <div class="app-container">
        <div class="main-content-area">
            
            <h1 class="header-title">Ticket Dashboard</h1>

            <div class="form-card">
                <h2 class="form-title">Add New Ticket</h2>
                <div class="form-fields">
                    <input
                        type="text"
                        placeholder="Ticket Title"
                        v-model="newTicketTitle"
                        class="input-field"
                    />
                    <textarea
                        placeholder="Description"
                        v-model="newTicketDesc"
                        class="input-field textarea-field"
                        rows="3"
                    ></textarea>
                    <button
                        @click="createTicket"
                        class="btn-submit"
                        :disabled="!newTicketTitle || !newTicketDesc"
                    >
                        Create Ticket
                    </button>
                </div>
            </div>

            <h2 class="list-title">Current Tickets ({{ tickets.length }})</h2>
            <div class="ticket-list">
                <div 
                    v-for="ticket in sortedTickets"
                    :key="ticket.id" 
                    class="ticket-item"
                >
                    <div class="ticket-info">
                        <h3 class="ticket-title-text">{{ ticket.title }}</h3>
                        <p class="ticket-description">{{ ticket.description }}</p>
                        <p :class="['ticket-status-text', getStatusClass(ticket.status)]">
                            Status: {{ ticket.status }}
                        </p>
                    </div>
                    <div class="ticket-actions">
                        <button
                            @click="toggleStatus(ticket.id, ticket.status)"
                            :class="['btn-status-toggle', getStatusClass(ticket.status)]"
                        >
                            <template v-if="ticket.status === 'Open'">Start Work</template>
                            <template v-else-if="ticket.status === 'InProgress'">Complete</template>
                            <template v-else>Re-open</template>
                        </button>
                        
                        <button
                            @click="deleteTicket(ticket.id)"
                            class="btn-delete"
                        >
                            Delete
                        </button>
                    </div>
                </div>
            </div>
            <p v-if="tickets.length === 0" class="no-tickets-message">
                No tickets found. Add one above!
            </p>
        </div>
    </div>
</template>

<style scoped>
.app-container {
    min-height: 100vh;
    background-color: #111827;
    color: #ffffff;
    padding: 1rem;
    font-family: Arial, sans-serif;
}
.main-content-area {
    max-width: 48rem;
    margin-left: auto;
    margin-right: auto;
    padding-top: 1rem;
    padding-bottom: 1rem;
}

.header-title {
    font-size: 2.25rem;
    font-weight: 700;
    color: #3b82f6;
    margin-bottom: 1.5rem;
}

.form-card {
    margin-bottom: 2rem;
    padding: 1.5rem;
    background-color: #1f2937;
    border-radius: 0.5rem;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.5);
}
.form-title {
    font-size: 1.5rem;
    font-weight: 600;
    color: #ffffff;
    margin-bottom: 1rem;
}
.form-fields {
    display: flex;
    flex-direction: column;
    gap: 1rem;
}
.input-field {
    width: 100%;
    padding: 0.75rem;
    border-radius: 0.25rem;
    background-color: #374151;
    color: #ffffff;
    border: 1px solid #4b5563;
    outline: none;
}
.input-field:focus {
    border-color: #3b82f6;
}
.textarea-field {
    resize: vertical;
}
.btn-submit {
    width: 100%;
    padding: 0.75rem;
    border-radius: 0.5rem;
    font-weight: 700;
    color: #ffffff;
    background-color: #10b981;
    transition: background-color 0.2s;
    cursor: pointer;
}
.btn-submit:hover:not(:disabled) {
    background-color: #059669;
}
.btn-submit:disabled {
    opacity: 0.6;
    cursor: not-allowed;
}

.list-title {
    font-size: 1.5rem;
    font-weight: 600;
    color: #ffffff;
    margin-bottom: 1rem;
}
.ticket-list {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
}
.ticket-item {
    padding: 1rem;
    background-color: #1f2937;
    border-radius: 0.5rem;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    gap: 0.5rem;
}
@media (min-width: 640px) {
    .ticket-item {
        flex-direction: row;
        align-items: center;
        gap: 1rem;
    }
}

.ticket-info {
    flex-grow: 1;
}
.ticket-title-text {
    font-size: 1.125rem;
    font-weight: 700;
    color: #facc15;
}
.ticket-description {
    color: #d1d5db;
    font-size: 0.875rem;
}
.ticket-status-text {
    font-weight: 600;
    font-size: 0.875rem;
    margin-top: 0.25rem;
}

.status-open {
    color: #f87171;
}
.status-in-progress {
    color: #fcd34d;
}
.status-closed {
    color: #4ade80;
}

.ticket-actions {
    display: flex;
    gap: 0.5rem;
    width: 100%;
}
@media (min-width: 640px) {
    .ticket-actions {
        width: auto;
    }
}

.btn-base {
    padding: 0.5rem 0.75rem;
    border-radius: 0.25rem;
    font-size: 0.875rem;
    font-weight: 600;
    color: #ffffff;
    transition: background-color 0.2s;
    cursor: pointer;
    text-align: center;
    flex-grow: 1;
}

.btn-status-toggle {
    composes: btn-base;
}
.btn-status-toggle.status-open {
    background-color: #6366f1;
}
.btn-status-toggle.status-open:hover {
    background-color: #4f46e5;
}
.btn-status-toggle.status-in-progress {
    background-color: #f59e0b;
}
.btn-status-toggle.status-in-progress:hover {
    background-color: #d97706;
}
.btn-status-toggle.status-closed {
    background-color: #16a34a;
}
.btn-status-toggle.status-closed:hover {
    background-color: #15803d;
}

.btn-delete {
    composes: btn-base;
    background-color: #ef4444;
}
.btn-delete:hover {
    background-color: #dc2626;
}

.no-tickets-message {
    color: #9ca3af;
    text-align: center;
    margin-top: 2rem;
    padding: 1rem;
    background-color: #1f2937;
    border-radius: 0.5rem;
}
</style>
